name: Compile DS Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup devkitPro environment
        uses: devkitpro/actions/setup@v2
        with:
          run: |
            dkp-pacman -Syyu --noconfirm
            dkp-pacman -S --noconfirm libnds default-makefiles grit

      - name: Build NDS ROM
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberQuest-NDS
          path: |
            *.nds
            
